#!/usr/bin/env bash
# Regenerate the Ansible inventory from Terraform state.
#
# Public IPs change on every stop/start, so hand-maintaining inventory.ini means
# editing it every morning and eventually chasing a "host unreachable" that is
# just a stale address. Generating it is also better practice, and worth a line
# in the write-up.
set -euo pipefail

cd "$(dirname "$0")/../terraform"

OUT="../ansible/inventory.ini"
BASTION="$(terraform output -raw bastion_public_ip)"
JUMP="-o StrictHostKeyChecking=accept-new -J ubuntu@${BASTION}"

{
  echo "# GENERATED by scripts/gen-inventory.sh — do not edit"
  echo "# $(date -u +%FT%TZ)"
  echo
  # Private IPs only — these nodes have no public address at all.
  echo "[web]"
  terraform output -json web_private_ips | jq -r '.[]'
  echo
  echo "[db_primary]"
  terraform output -raw db_primary_private_ip
  echo
  echo
  echo "[db_replica]"
  terraform output -raw db_replica_private_ip
  echo
  echo
  echo "[bastion]"
  echo "${BASTION}"
  echo
  echo "[all:vars]"
  echo "ansible_user=ubuntu"
  echo "ansible_ssh_private_key_file=~/.ssh/ha-lab.pem"
  echo "db_primary_private_ip=$(terraform output -raw db_primary_private_ip)"
  echo "vpc_cidr=$(terraform output -raw vpc_cidr)"
  echo "admin_cidr=$(terraform output -raw admin_cidr)"
  echo "backup_bucket=$(terraform output -raw backup_bucket)"
  echo "kms_key_id=$(terraform output -raw kms_key_id)"
  echo
  # Every private group reaches its hosts by jumping through the bastion.
  for grp in web db_primary db_replica; do
    echo "[${grp}:vars]"
    echo "ansible_ssh_common_args='${JUMP}'"
    echo
  done
  echo "[bastion:vars]"
  echo "ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'"
} > "$OUT"

echo "Wrote $OUT (bastion ${BASTION})"
