#!/usr/bin/env bash
# Refresh Cloudflare's edge IPv4 ranges in both places that need them.
#
# The ALB security group and nginx's set_real_ip_from must agree. Hardcoding
# them in two files invites drift, so this writes both from the same fetch.
#
# Cloudflare does change these. Run it before each rebuild, and be aware that a
# stale list here shows up as "some visitors get a connection timeout" rather
# than as any obvious error.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
TF_OUT="$HERE/../terraform/cloudflare_ranges.auto.tfvars"
# Must live inside group_vars/all/ — a file at group_vars/cloudflare.yml would
# be read as variables for a GROUP called "cloudflare", which does not exist,
# and Ansible would silently ignore it.
ANS_OUT="$HERE/../ansible/group_vars/all/cloudflare.yml"

echo "==> Fetching https://www.cloudflare.com/ips-v4"
RANGES="$(curl -fsS https://www.cloudflare.com/ips-v4)"

if [[ -z "$RANGES" ]]; then
  echo "FATAL: empty response — refusing to write an empty allowlist." >&2
  exit 1
fi

COUNT=$(echo "$RANGES" | grep -c '/')
if [[ "$COUNT" -lt 10 ]]; then
  echo "FATAL: only $COUNT ranges returned, expected ~15. Refusing to write." >&2
  exit 1
fi

{
  echo "# GENERATED by scripts/update-cloudflare-ranges.sh — $(date -u +%FT%TZ)"
  echo "cloudflare_ipv4_ranges = ["
  echo "$RANGES" | while read -r cidr; do
    [[ -n "$cidr" ]] && printf '  "%s",\n' "$cidr"
  done
  echo "]"
} > "$TF_OUT"

{
  echo "---"
  echo "# GENERATED by scripts/update-cloudflare-ranges.sh — $(date -u +%FT%TZ)"
  echo "cloudflare_ipv4_ranges:"
  echo "$RANGES" | while read -r cidr; do
    [[ -n "$cidr" ]] && printf '  - %s\n' "$cidr"
  done
} > "$ANS_OUT"

echo "==> Wrote $COUNT ranges to:"
echo "    $TF_OUT"
echo "    $ANS_OUT"
echo
echo "Re-run terraform apply and the nginx_app role for these to take effect."
